### ISSUE TITLE
cleaning up imports

### ISSUE THREAD

**Issue by cmccomb** [rhaiscript/rhai-sci#10]
@cmccomb   looking good!  Especially making lots of dependencies option.

I'd suggest adding a feature to gate `rustyline`, since it may not be always necessary unless the user is writing a REPL.

Also, maybe a feature to gate `rand` -- but since this is a scientific computing package, maybe random numbers should be standard...

_Originally posted by @schungx in https://github.com/rhaiscript/rhai-sci/issues/9#issuecomment-1207113418_

**Comment by cmccomb** [comment]
Good points @schungx!

> I'd suggest adding a feature to gate `rustyline`, since it may not be always necessary unless the user is writing a REPL.

I run a REPL for quick testing but you're right that it doesn't need to be part of this crate. I'll clean this up. 

> Also, maybe a feature to gate `rand` -- but since this is a scientific computing package, maybe random numbers should be standard...

I like the idea of providing some more control to the user when it comes to larger dependencies. How about gating `rand`, `nalgebra`, etc, but including them all under `default-features`?

**Comment by schungx** [comment]
> I like the idea of providing some more control to the user when it comes to larger dependencies. How about gating `rand`, `nalgebra`, etc, but including them all under `default-features`?

That would be very good because it gives the user maximum flexibility to only include what he needs.
