### ISSUE TITLE
prctile bound issues

### ISSUE THREAD

**Issue by bogzbonny** [rhaiscript/rhai-sci#15]
the `prctile` function panics when a percentile value provided is outside of the range 0..100 
I imagine it should return an error instead of panicking 

Additionally `prctile` should return the max value when a percentile of 100 is provided (instead of panicking as it currently does). I wonder if it does this because of the inaccuracies of f64 (does f64 represent the value 100 as over 100?).
The panic is: 'attempt to subtract with overflow', rhai-sci-0.1.9/src/misc.rs:76:25

**Comment by schungx** [comment]
I'm doing a refactor of the code so I'll put in a fix also.

**Comment by bogzbonny** [comment]
Sweet!

**Comment by schungx** [comment]
@bogzbonny   I see that the maintainer has merged in changes that fix `prctile` on out-of-bound parameters.  You can pull from this repo to try out the fix.
