### ISSUE TITLE
Checking the first element of array

### ISSUE THREAD

**Issue by schungx** [rhaiscript/rhai-sci#5]
In some of the array functions, I see code that checks the first element and then assumes the rest of the array to be of the same type (usually by checking whether we're working with an `INT` or `FLOAT` array):

```rust
if arr[0].is::<INT>() {
    :
} else if arr[0].is::<FLOAT>() {
    :
} ...
```

This is perhaps necessary for statically-typed languages, but Rhai is dynamic so this restriction is rarely necessary as the users may expect to be able to freely mix `INT` with `FLOAT`.

For example, we can consider to do this instead: Assume the array is an `INT` if and only if _all_ elements are `INT`.  Otherwise, convert to `FLOAT` array.  This is consistent with treatment of `FLOAT` in Rhai, which is: `a + b` is only `INT` if and only if `a` and `b` are both `INT`.

```rust
let (ints, floats) = arr.iter().fold((0, 0), |(i, f), x| {
    if x.is::<INT>() {
        (i + 1, f)
    } else if x.is::<FLOAT>() {
        (i, f + 1)
    } else {
        (i, f)
    }
});

if ints + floats < arr.len() {
    // raise error as some elements are not numeric
} else if floats == 0 {
    let i_vec = arr.iter().map(|x| x.as_int().unwrap()).collect::<Vec<_>>();
} else {
    let f_vec = arr
        .iter()
        .map(|x| {
            if x.is::<FLOAT>() {
                x.as_float().unwrap()
            } else {
                x.as_int().unwrap() as FLOAT
            }
        })
        .collect::<Vec<_>>();
}
```

**Comment by cmccomb** [comment]
Thanks for providing the sample code! This check-convert block is one of several that shows up frequently, so I will address this over time with some other de-duplications.

**Comment by schungx** [comment]
A slight alternative can be used to early return when you encounter an error or a `FLOAT`...

```rust
    let is_all_int = arr
        .iter()
        .try_fold((), |_, x| {
            if x.is::<FLOAT>() {
                Err(false) // Err(false) = some FLOAT
            } else if x.is::<INT>() {
                Ok(true) // Ok(true) = all INT
            } else {
                Err(true) // Err(true) = type error
            }
        }).or_else(|err| if err { Err(......) } else { Ok(false) })?;
```
